"""Explicit local synthetic database target and per-test schema lifecycle."""
import uuid
from sqlalchemy import create_engine, text
from sqlalchemy.engine import make_url

_admin = None
_url = None
_schemas = []


def configure(raw_url):
    global _admin, _url
    url = make_url(raw_url)
    host = url.query.get('host') or url.host or ''
    if (url.get_backend_name() != 'postgresql'
            or not (url.database or '').startswith('ftf_security_validation')
            or not (host in {'localhost', '127.0.0.1', '::1'}
                    or host.startswith('/private/tmp/ftf-security'))):
        raise ValueError('Requires a local ftf_security_validation* synthetic database')
    if 'options' in url.query:
        raise ValueError('Do not supply custom PostgreSQL options')
    _url = url
    _admin = create_engine(url, echo=False, hide_parameters=True)


def isolated_engine(*args, **kwargs):
    if _admin is None:
        raise RuntimeError('Use run_postgres.py with an explicit synthetic target')
    name = 'ftf_validation_' + uuid.uuid4().hex
    with _admin.begin() as conn:
        conn.execute(text('CREATE SCHEMA ' + name))
    _schemas.append(name)
    query = dict(_url.query)
    query['options'] = '-csearch_path=' + name
    return create_engine(_url.set(query=query), echo=False, hide_parameters=True)


def cleanup():
    """Remove only schemas generated by this process; never reset the database."""
    if _admin is not None:
        try:
            for name in _schemas:
                with _admin.begin() as conn:
                    conn.execute(text('DROP SCHEMA ' + name + ' CASCADE'))
        finally:
            _admin.dispose()
