"""Exact serialization contracts; generation-only compact failures stay private."""
from copy import deepcopy
from dataclasses import asdict, FrozenInstanceError, is_dataclass
import hashlib
import json

import pytest

from backend import feature_flags as ff, trade_service as ts
from backend import trade_gen_owner as owner, trade_gen_bilateral as incumbent
from backend import trade_gen_bilateral_candidate as candidate
from backend.tests.test_bilateral_candidate import companion_world, terms
from backend.tests.test_bilateral_contracts import favorable, world


@pytest.fixture(autouse=True)
def isolate(monkeypatch):
    monkeypatch.setattr(ff, '_flags_cache', dict(ff.DEFAULT_FLAGS))
    monkeypatch.setattr(ts, '_cfg', dict(ts._DEFAULT_CFG))


CASES=('ordinary','neutral','unknown','partial','invalid_floor','exact','pair_budget',
       'total_budget','expired','untouchable','last_wins','previous_disposition')
# Captured before runtime edits from 6c53caf9, not regenerated by the asserted
# implementation. Values bind declared card fields/report and external proof JSON.
REFERENCES = {
    'ordinary': {'candidate': '8e5b7e0fa113d979d0ef7b2c0be4d038a1fea15a92675927fe7c2085889cd3e1',
        'incumbent': 'f3d9a2e7b048a7980e7070387bb7b135ba16602f88d78b2e55c1f92f87283ad3',
        'external': '89c8d3eabb941abbcbd04d4255ad3faffd6adbb034cfa3850b8375d6cd6e90c0'},
    'neutral': {'candidate': '6fd728b1b2616348edc9a5513c97dc5a4755a1ce2c58aa96fe86e4691167a005',
        'incumbent': '937e2e227a0768c20b6838d7ecc828438ace0ce78f5cecf6ce3033ef25cfe342',
        'external': 'd31500ee37c5a3d95a35be968a566fbfde01b3c8e0d74715b780a32dd6c9a928'},
    'unknown': {'candidate': '830034888066a552cbcf8d4879286d6db9d41236745bb3baa53818c3ccaebc7b',
        'incumbent': '9ab86b81608c6a46d42d9568bfb4da65b43b3915b2f0ec8aef829aff72c48f69',
        'external': 'c2f6b241c7fd1f2698c939c07a2348cbe73e189d4fe45f4a6906ea2033a5d0e7'},
    'partial': {'candidate': '345f55f3cfc1fce6d1e766c4d6e42b236fe1671871778e4b5d32b96052ee720a',
        'incumbent': 'e525b9c01a0d16c5e0a2e8f5572687a374a0de1f76d7bbf5cc8dc1c2d1ba7592',
        'external': '1d19ce35a0f7f3e104f3d3a0dc17a25ed7cc688a4982ab4cbe5f0c453b936b36'},
    'invalid_floor': {'candidate': 'c12e795ac9764f90b0a6b7d1a55b030274a9f2f5554a6ebef8c38a7c7792fe31',
        'incumbent': '79c3db38faea69f744c0a15083543424ed36a6dc10e4c6101b63f26014f35ea3',
        'external': '0cd794126bfdf37f024366005d62f078f4671ce846a36e445f4d0cca6a1d7796'},
    'exact': {'candidate': '01a9c1af86870e5bb719439c27efd3750d9179b986c86fcf2cc7024899b70f7c',
        'incumbent': 'f976616f8566fb433e8575d59f71863de83e2fd0701f19ae9f69154f0e3505a6',
        'external': '5cab88124367d4b45e5ea36be257827f07bdadb26c20692b59b3a6ab616cc238'},
    'pair_budget': {'candidate': 'b9f156f1979da15e156d06eaf2b44ce7a855ff6986d046a1d102c87b54fef4d9',
        'incumbent': 'd81a4cc66745da842a07ef63f1116ee8f046fe748c456b3ce50644850a148402',
        'external': '89c8d3eabb941abbcbd04d4255ad3faffd6adbb034cfa3850b8375d6cd6e90c0'},
    'total_budget': {'candidate': '6bfd93f110de06683207e3059eae9fad416e7fb6a06f1d0702f3cdc880cfe72c',
        'incumbent': '410b75ecbb70eaeae1b6c39ddadffd019fe11c0cd6832a1db2a360cf9f3be041',
        'external': '89c8d3eabb941abbcbd04d4255ad3faffd6adbb034cfa3850b8375d6cd6e90c0'},
    'expired': {'candidate': '040b03246ce36632a06a16117fb0040f9f2836dea292cbd0e3fe8b1d28313fa0',
        'incumbent': 'c750fb13bdb1f65797e9306a15161f98335e80ff9dcc603135919ff0507fcc51',
        'external': '24cecbb45ed899c40e260705afeeefc95898888a336214b96c3258094034614f'},
    'untouchable': {'candidate': '4b32163a94ab29d4677363f6cd59647b5f75d9ec4f699b5133a546a37b7ae5dc',
        'incumbent': '805e1b951eb634d8fa2b42b174b3cbaa011c5a565521fce12e0818bb686862ab',
        'external': 'f5de8e385682bf8f79530ff533455e2d57d2c6a40726750dd11b882d0054445d'},
    'last_wins': {'candidate': '64935fb61c2681c7270be9d08ec58e89ffb4c60feaa01e3c83f94280c041aa9f',
        'incumbent': '6045a27f624c6baa027376d8606508655b8839d8d02f73aabc51f163de948dad',
        'external': '9140e09f05362842fa4a1e49813452212c63da28c92f4d9d15ca5e4b64f5841b'},
    'previous_disposition': {'candidate': '0b93f21197db5942e7c4cff93ed798263e6eb996eee8187e937773a6ec01654a',
        'incumbent': '19513a53fc717cf893f400a16e2a93e9725bd228315b4c3f464d5fa2bcbdbe24',
        'external': '1dd15b8745cfead0e8d6e726aa3740b3b79e4ae12ab8f118f1ff7a1d0d91528b'},
}

# Separately captured with vars(card) from immutable checkpoint 6c53caf9 module
# sources. Dynamic owner_evaluation includes its byte-exact snapshot_json string.
DYNAMIC_REFERENCES = {
    'ordinary': ('6f38d797c860c909d4a28de55531f751fa58206afe2194f8d53f793dd40c0199', '8828c109d8a2d7be27bb3debb0ae699ca1d14318d26b614ea91008efac1b093f'),
    'neutral': ('6fd728b1b2616348edc9a5513c97dc5a4755a1ce2c58aa96fe86e4691167a005', '937e2e227a0768c20b6838d7ecc828438ace0ce78f5cecf6ce3033ef25cfe342'),
    'unknown': ('7a531bc6eb3547ea84f51582031f02cade04f4b9aa4ba299a3cfc645af3213d7', '0d3dad30b04612020432c98c20d2b41bdd6eb1f3c8af0ce7445fc68e76bced5d'),
    'partial': ('602fe64c90c97fb8f1b20e0febd75ad4935d5a63de37d6fcb0a8400bd2a5c0ce', 'b4a4d79247f4f0f1068bff46022d90d056f6154437c54561ebf5d374e9c1914e'),
    'invalid_floor': ('c12e795ac9764f90b0a6b7d1a55b030274a9f2f5554a6ebef8c38a7c7792fe31', '79c3db38faea69f744c0a15083543424ed36a6dc10e4c6101b63f26014f35ea3'),
    'exact': ('5117ef731b29267865ebc39daca078cbf6d30549a8864efb4a41005cb86092f3', '58b8853a5150e011596dbfefb07636250156010527a02dce49efec133ea377c3'),
    'pair_budget': ('a5b0ad47e8cd9f367f0981854226ac211956e16d5b2e2f0e436b52af5082bcde', '75e692058c8c33c6e4e7ec89179634509b40834bd62b807f7d4da02e38195dfb'),
    'total_budget': ('617c133177d052c1362a4c08799ffc24ab7785d20efdd7511bacbc9351680039', '1886de584108a91c457f143f178c97193515cb3a4196ac4f84b934ae6c82a343'),
    'expired': ('040b03246ce36632a06a16117fb0040f9f2836dea292cbd0e3fe8b1d28313fa0', 'c750fb13bdb1f65797e9306a15161f98335e80ff9dcc603135919ff0507fcc51'),
    'untouchable': ('6d4120e7b38f510ec941bae7b6b56578ae78d50a0ef321000259840186ac5e49', 'b45f0121cf17d10feaf14557b2c5e7e5881541967bd92339b0e0ed5b26f95691'),
    'last_wins': ('64935fb61c2681c7270be9d08ec58e89ffb4c60feaa01e3c83f94280c041aa9f', '6045a27f624c6baa027376d8606508655b8839d8d02f73aabc51f163de948dad'),
    'previous_disposition': ('b4c10e1bf09c79ae7990efad7fb715bd56ed60f0bad8a28f08333d6f64d66a83', 'eb75f548746de1ab8428527f3e5855cc31ca2fc858d2b44c62378231622099b0'),
}


def arguments(case):
    args=companion_world()
    if case=='neutral':args=world()
    elif case=='unknown':args['opponent_sources']={'partner':{}}
    elif case=='partial':args['pinned_give_players']=['give','missing']
    elif case=='invalid_floor':args['fairness_threshold']=float('nan')
    elif case=='exact':args.update(pinned_give_players=['give'],exact_give=True)
    elif case=='pair_budget':args['config']={'owner_pair_budget':1}
    elif case=='total_budget':args['config']={'owner_total_budget':1}
    elif case=='expired':args['manager_preferences']={'viewer':{'expired_pick_ids':['give']}}
    elif case=='untouchable':args['manager_preferences']={'partner':{'untouchables':['target']}}
    elif case=='last_wins':
        args=favorable(outlook='jets',opponent_outlooks={'partner':'jets'},
            manager_preferences={'viewer':{'expired_pick_ids':['give'],'own_next_draft_pick_ids':['give']},
                                 'partner':{'expired_pick_ids':['target'],'own_next_draft_pick_ids':['target']}})
    elif case=='previous_disposition':args['exclusion_keys']={(frozenset(['give']),frozenset(['target']))}
    return args


def digest(value):
    return hashlib.sha256(json.dumps(value,sort_keys=True,separators=(',',':'),allow_nan=False).encode()).hexdigest()


def generated_value(module,args,*,dynamic=False):
    cards,report=module.generate_bilateral_trades(**deepcopy(args))
    values=[dict(vars(c)) if dynamic else asdict(c) for c in cards]
    for card in values:
        for key in ('trade_id','created_at','expires_at'):card.pop(key,None)
    data=report.as_dict();data.pop('elapsed_seconds',None)
    def frozen(value):
        if is_dataclass(value):return asdict(value)
        raise TypeError(type(value).__name__)
    return json.loads(json.dumps([values,data],default=frozen,allow_nan=False))


def external_cards(args):
    return [terms(args,['give'],['target']),terms(args,['missing'],['target']),
            terms(args,['give','give'],['target']),terms(args,['extra'],['target'])]


@pytest.mark.parametrize('give,eligible',[('give',True),('extra',False)])
def test_named_red_core_freezes_only_once(monkeypatch,give,eligible):
    args=companion_world();search=candidate._Search(**args);calls=[];dump=owner._dump
    def observe(data):
        if 'eligible' in data and 'selection' in data:calls.append(data)
        return dump(data)
    monkeypatch.setattr(owner,'_dump',observe)
    with ts._cfg_override(search.config),ts.stud_tax_override('market'):
        proof=search._core(terms(args,[give],['target']))
    assert proof.eligible is eligible and len(calls)==1
    assert isinstance(proof,owner.OwnerDecisionContext)
    assert proof.as_dict()['generator_version']==candidate.VERSION


def test_named_red_generation_never_serializes_final_rejected_json(monkeypatch):
    dump=owner._dump
    def no_rejected(data):
        assert data.get('eligible') is not False, 'unused internal rejection JSON serialized'
        return dump(data)
    monkeypatch.setattr(owner,'_dump',no_rejected)
    cards,report=candidate.generate_bilateral_trades(**companion_world())
    assert cards and report.as_dict()['rejections']
    assert all(isinstance(c.owner_evaluation,owner.OwnerDecisionContext) for c in cards)


@pytest.mark.parametrize('case',CASES)
def test_preintegration_native_report_and_external_diagnostics(case):
    args=arguments(case)
    external=candidate.evaluate_bilateral_trades(external_cards(args),**deepcopy(args))
    assert all(isinstance(proof,owner.OwnerDecisionContext) for proof in external)
    assert digest([asdict(p) for p in external])==REFERENCES[case]['external']
    assert asdict(candidate.evaluate_bilateral_trade(external_cards(args)[0],**deepcopy(args)))==asdict(external[0])
    assert digest(generated_value(candidate,args))==REFERENCES[case]['candidate']
    assert digest(generated_value(incumbent,args))==REFERENCES[case]['incumbent']
    assert digest(generated_value(candidate,args,dynamic=True))==DYNAMIC_REFERENCES[case][0]
    assert digest(generated_value(incumbent,args,dynamic=True))==DYNAMIC_REFERENCES[case][1]


def test_final_bilateral_reason_precedence_is_not_short_circuited():
    args=arguments('last_wins')
    external=candidate.evaluate_bilateral_trade(terms(args,['give'],['target']),**args)
    assert external.reason=='tanking_own_next_draft_pick'
    search=candidate._GenerationSearch(**args)
    with ts._cfg_override(search.config),ts.stud_tax_override('market'):
        compact=search.evaluate(terms(args,['give'],['target']))
    assert compact.reason==external.reason and not compact.eligible
    # Owner-level early market failure retains precedence before bilateral guards.
    args=arguments('expired')
    rejected=candidate.evaluate_bilateral_trade(terms(args,['extra'],['target']),**args)
    assert rejected.reason=='market_floor'


def test_core_cache_alias_and_companion_status_access():
    args=companion_world();search=candidate._GenerationSearch(**args)
    card=terms(args,['extra'],['target'])
    with ts._cfg_override(search.config),ts.stud_tax_override('market'):
        proof=search._core(card)
        assert proof is search._core(card) is search.evaluate(card)
    assert not proof.eligible and search._decisions[incumbent._identity(card)] is proof
    with pytest.raises(FrozenInstanceError):proof.reason='eligible'


@pytest.mark.parametrize('field',['as_dict','snapshot_json','matches','effective_floor','give_ids','receive_ids','user_id'])
def test_discarded_fields_fail_even_with_getattr_default(field):
    args=companion_world();search=candidate._GenerationSearch(**args)
    with ts._cfg_override(search.config),ts.stud_tax_override('market'):
        proof=search._core(terms(args,['extra'],['target']))
    with pytest.raises(RuntimeError,match='Internal generation rejection'):
        value=getattr(proof,field,None)
        if callable(value):value()


def test_new_snapshot_consumer_aborts_real_generation(monkeypatch):
    evaluate=candidate._Search.evaluate
    def consumer(self,card,**kwargs):
        proof=evaluate(self,card,**kwargs)
        if not proof.eligible:proof.as_dict()
        return proof
    monkeypatch.setattr(candidate._Search,'evaluate',consumer)
    with pytest.raises(RuntimeError,match='Internal generation rejection'):
        candidate.generate_bilateral_trades(**companion_world())


def test_external_callers_cannot_select_compact_mode():
    args=companion_world();cards=external_cards(args)
    with pytest.raises(TypeError):
        candidate.evaluate_bilateral_trades(cards,**args,compact_final_rejections=True)
    expected=[asdict(p) for p in candidate.evaluate_bilateral_trades(cards,**args)]
    args['config']={'compact_final_rejections':True}
    assert [asdict(p) for p in candidate.evaluate_bilateral_trades(cards,**args)]==expected


def test_final_term_efficiency_proof_is_still_full_and_exact():
    args=companion_world();cards,_=candidate.generate_bilateral_trades(**args)
    full=candidate.evaluate_bilateral_trades(cards,**args)
    for card,proof in zip(cards,full):
        assert proof.matches(card) and isinstance(card.owner_evaluation,owner.OwnerDecisionContext)
        assert proof.snapshot_json==card.owner_evaluation.snapshot_json
        assert 'term_efficiency' in proof.as_dict()


def test_explicit_and_partial_generation_retain_complete_selection_proofs():
    partial=arguments('partial')
    cards,report=candidate.generate_bilateral_trades(**partial)
    assert cards and report.as_dict()['partial_search']
    assert all(card.owner_evaluation.as_dict()['selection']['coverage']=='partial' for card in cards)
    explicit=companion_world(pinned_give_players=['give','extra'])
    selected,_=candidate.generate_bilateral_trades(**explicit)
    assert selected and all({'give','extra'} <= set(card.give_player_ids) for card in selected)
    assert all(card.owner_evaluation.as_dict()['selection']['coverage']=='full' for card in selected)


@pytest.mark.parametrize('rejected_only',[False,True])
@pytest.mark.parametrize('bad,error',[(float('nan'),ValueError),(object(),TypeError)])
def test_malformed_caller_provenance_still_aborts_actual_generation(rejected_only,bad,error):
    # The immutable prechange module rejects both through allow_nan=False JSON.
    # Even when all internal decisions compact, the required report still fails
    # serialization: no returned offer inventory can bypass this boundary.
    args=companion_world()
    args['manager_preferences']={'viewer':{}}
    if rejected_only:
        args['manager_preferences']['viewer']['expired_pick_ids']=['give','extra']
        cards,report=candidate.generate_bilateral_trades(**args)
        assert cards==[] and report.as_dict()['rejections']
    args['manager_preferences']['viewer']['market_source_snapshot']={'bad':bad}
    with pytest.raises(error):candidate.generate_bilateral_trades(**args)
